name: naked_ui

packages:
  - packages/*

  # Development commands
  get:
    description: Get dependencies for all packages
    run: flutter pub get

  analyze:
    description: Run static analysis
    run: flutter analyze

  format:
    description: Format all Dart code
    run: dart format .

  format:check:
    description: Check if all Dart code is formatted
    run: dart format --set-exit-if-changed .
  
  test:ci
    run: melos exec -- flutter test 
    description: Run flutter test
    packageFilters:
      dirExists: test

  # Build commands
  build:example:
    description: Build example app for macOS
    run: flutter build macos
    packageFilters:
      dirExists: example

  # CI/CD commands
  ci:
    description: Run CI checks (format, analyze, test)
    run: |
      melos format:check &&
      melos analyze &&
      melos test:all

# IDE settings
ide:
  intellij:
    enabled: false

command:
  version:
    linkToCommits: true
    workspaceChangelog: true