include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    comment_references: true
    prefer_relative_imports: true
    public_member_api_docs: true
    slash_for_doc_comments: true
