name: Prepare Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to generate changelog for'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-changelog:
    name: Run auto-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: ardalanamini/auto-changelog@v4
        with:
          mention-authors: false  
          mention-new-contributors: false
          version: ${{ inputs.version }}