name: Deploy Kitchen Sink (Web)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub get
        working-directory: example
      - name: Ensure web platform files
        run: |
          if [ ! -d "web" ]; then
            flutter create --platforms web .
          fi
        working-directory: example
      - run: flutter config --enable-web
      - run: flutter build web --release --base-href /naked_ui/
        working-directory: example
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
          force_orphan: true
          publish_branch: gh-pages
