name: CI

on:
  push:
  pull_request:

jobs:
  unit:
    name: Unit & Widget Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Run tests
        run: flutter test -j 1

  integration-macos:
    if: ${{ env.RUN_INTEGRATION == '1' }}
    name: Integration Tests (macOS)
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - integration_test/components/naked_button_integration.dart
          - integration_test/components/naked_checkbox_integration.dart
          - integration_test/components/naked_radio_integration.dart
          - integration_test/components/naked_slider_integration.dart
          - integration_test/components/naked_tabs_integration.dart
          - integration_test/components/naked_textfield_integration.dart
          - integration_test/components/naked_tooltip_integration.dart
          - integration_test/components/naked_accordion_integration.dart
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub get
        run: flutter pub get
      - name: Pub get (example)
        run: flutter pub get
        working-directory: example
      - name: Run integration test
        working-directory: example
        run: flutter test -r compact ${{ matrix.file }} -d macos --no-enable-impeller
