name: Flutter CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - docs.json

  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - docs.json

# Cancel any in-progress runs of the same workflow for the same PR/branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.32.0
          cache: true

      - name: Install root dependencies
        run: flutter pub get

  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Analyze root project
        run: flutter analyze

  dcm:
    name: DCM Analysis
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install DCM
        uses: CQLabs/setup-dcm@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        run: dcm analyze .
        shell: bash

  test_and_coverage:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest
    needs: [setup, dcm]
    steps:
      - name: Run root tests
        run: flutter test --coverage 

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
        with:
          ref: v2.3

      - name: Report Code Coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 85
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}